- hosts: localhost

  tasks:

    - name: apt-get update
      apt:
        update_cache: yes


    - name: Instalacja paczek kasnet/xkasnet ABC - SURFACE
      shell: |
         export TERM="xterm-256color"; export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"; export SHELL="/bin/bash"; /usr/bin/apt install kasnet-server-2.1.335=2.1.335r202109030813~bionic-1 kasnet-src-2.1.335=2.1.335r202109030813~bionic-1 kasnet-tools-2.1.335=2.1.335r202109030813~bionic-1 kasnet-libwaga-2.1.335=2.1.335r202109030813~bionic-1 xkasnet-client-2.2.16=2.2.16r202109131430~bionic-1 xkasnet-client-ec-2.2.16=2.2.16r202109131430~bionic-1 xkasnet-libnative-jni-2.2.16=2.2.16r202109131430~bionic-1 --yes --allow-downgrades --allow-remove-essential --allow-change-held-packages
      args:
        executable: /bin/bash
      when: ansible_product_name == 'Surface Go'

    - name: ustawiam zmienne
      ignore_errors: true
      community.mysql.mysql_query:
        login_db: 'kasa'
        query:
        - 'replace into StanKasy values ("serv.przez.symmetric",1);'
        - 'replace into StanKasy values ("promocje.konflikty.ec",1);'
        - 'replace into StanKasy values ("ksk.gazetki.wszystkie.sklepy",0);'
        - 'replace into StanKasy values ("Promocje.AutomatycznePrzeladowanie",1);'
        single_transaction: yes

    - name: Sprawdzam czy jest config xkasnet'a
      stat:
        path: '/home/kasa/CONFIG'
      register: stat_result

    - name: Tworze config kasy - SURFACE new layout
      ansible.builtin.lineinfile:
        path: '/home/kasa/CONFIG'
        line: kasa.config-1700x1200-ecabc-new-layout
        create: yes
      when: ansible_product_name == 'Surface Go' and not stat_result.stat.exists

    - name: Zmiana rozdzielczosci - Surface
      replace:
        path: '/home/kasa/CONFIG'
        regexp: '{{ item.regexp }}'
        replace: '{{ item.line }}'
        backup: yes
      with_items:
        - { regexp: '^kasa.*$', line: 'kasa.config-1700x1200-ecabc-new-layout' }
      when: ansible_product_name == 'Surface Go' and stat_result.stat.exists


    - name: Usuwam .cache
      file:
        state: absent
        path: '/home/xkasnet/.cache'
      ignore_errors: yes
