- hosts: localhost

  tasks:

    - name:  Instalacja paczek kasnet/xkasnet ABC - SURFACE
      apt:
        name:
          - xkasnet-client-2.2.16=2.2.16r202109131430~bionic-1
          - xkasnet-client-ec-2.2.16=2.2.16r202109131430~bionic-1
          - xkasnet-libnative-jni-2.2.16=2.2.16r202109131430~bionic-1
          - kasnet-libwaga-2.1.335=2.1.335r202109030813~bionic-1
          - kasnet-server-2.1.335=2.1.335r202109030813~bionic-1
          - kasnet-src-2.1.335=2.1.335r202109030813~bionic-1
          - kasnet-config-2.1.335=2.1.335r202109030813~bionic-1
          - kasnet-tools-2.1.335=2.1.335r202109030813~bionic-1
        state: present
        force: yes
        update_cache: yes
      when: ansible_product_name == 'Surface Go'

    - name: Sprawdzam czy jest config xkasnet'a
      stat:
        path: '/home/kasa/CONFIG'
      register: stat_result

    - name: Tworze config kasy - SURFACE new layout
      ansible.builtin.lineinfile:
        path: '/home/kasa/CONFIG'
        line: kasa.config-1700x1200-ecabc-new-layout
        create: yes
      when: ansible_product_name == 'Surface Go' and not stat_result.stat.exists

    - name: Zmiana rozdzielczosci - Surface
      replace:
        path: '/home/kasa/CONFIG'
        regexp: '{{ item.regexp }}'
        replace: '{{ item.line }}'
        backup: yes
      with_items:
        - { regexp: '^kasa.*$', line: 'kasa.config-1700x1200-ecabc-new-layout' }
      when: ansible_product_name == 'Surface Go' and stat_result.stat.exists


    - name: Usuwam .cache
      file:
        state: absent
        path: '/home/xkasnet/.cache'
      ignore_errors: yes
